module.exports = {
  SA: 'SA',
  ADMIN_OPERATIONS: 'ADMIN_OPERATIONS', 
  SA_READONLY: 'SA_READONLY',
  COMPANY_SA: 'COMPANY_SA',
  COMPANY_PA: 'COMPANY_PA',
  INTERNAL_API_USER: 'INTERNAL_API_USER'
};